[package]
name = "smart-home-in-rust-with-home-assistant"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "smart_home_in_rust_with_home_assistant"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.40"
chrono-tz = "0.10.1"
derive_more = { version = "2.0.1", features = [
    "display",
    "from",
    "into",
    "try_from",
    "try_into",
] }
ijson = "0.1.4"
itertools = "0.14.0"
pyo3 = { version = "0.24.0", features = [
    "auto-initialize",
    "chrono",
    "chrono-tz",
] }
pyo3-async-runtimes = { version = "0.24.0", features = ["tokio-runtime"] }
serde_json = "1.0.140"
shadow-rs = { version = "1.0.1", default-features = false }
snafu = "0.8.5"
strum = { version = "0.27.1", features = ["derive"] }
tokio = { version = "1.32.0", features = ["rt", "rt-multi-thread", "time"] }
tracing = "0.1.37"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.17"
ulid = "1.2.0"

[build-dependencies]
shadow-rs = "1.0.1"
