[package]
name = "emitter-and-signal"
version = "0.1.0"
edition = "2021"
license = { workspace = true }

[dependencies]
deranged = { workspace = true }
ext-trait = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
